version: "3"

services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"

  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
